[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "multifit"
dynamic = ["version"]
description = 'fit multiple gamma spectra simultaneously'
requires-python = ">=3.11"
dependencies = [
	"attrs",
	"docopt-ng",
	"iminuit",
	"matplotlib",
	"numba_stats",
	"numpy",
	"pyyaml",
	"pytest",
]
authors = [
	{ name = "Johannes Sørby Heines", email = "j.s.heines@protonmail.ch" },
]
keywords = [
	"RDDS",
	"gamma spectroscopy",
	"fitting",
	"minuit",
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Programming Language :: Python :: 3.11",
	"Intended Audience :: Science/Research",
	"Topic :: Scientific/Engineering :: Physics",
]

[tool.hatch.version]
path = "./src/multifit/__about__.py"

[project.scripts]
multifit = "multifit.cli:main"

[tool.hatch.build.target.sdist]
exclude = [
	"/.github",
	"/doc",
]

[tool.hatch.build.targets.wheel]
packages = ["src/multifit"]

[tool.hatch.envs.dev]
python = "3.11"
dependencies = [
	"cmcrameri",
	"pandas",
	"pytest",
	"ipython"
]

[tool.pytest.ini_options]
adopts = [
	"--impoert-mode=importlib",
]
